version: '3.2'

services:
  event-handler:
    build: ./
    ports:
      - "8081:8081"
  # elasticsearch:
  #   image: elasticsearch:8.10.4
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false