version: '3.2'

services:
  postgres_facility:
    image: postgres:15.5-alpine
#    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: hybridcloud
#      POSTGRES_INITDB_ARGS: -e POSTGRES_DB=hybridcloud -e POSTGRES_USER=postgres -e POSTGRES_PASSWORD=postgres -v ./hybridcloud_dump.sql:/docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./hybridcloud_dump.sql:/docker-entrypoint-initdb.d/hybridcloud_dump.sql
    ports:
      - "5433:5432"
    networks:
      - facility
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s

  facility-manager:
    build: ./
    ports:
      - "8080:8080"
    networks:
      - facility
    depends_on:
      postgres_facility:
        condition: service_healthy
    environment:
      POSTGRES_TIPPERS_URL: jdbc:postgresql://postgres_facility:5432/hybridcloud
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: postgres
      DIR_MONITOR_PATH: /app/filewatch
    volumes:
      - ./monitoring:/app/filewatch

  # elasticsearch:
  #   image: elasticsearch:8.10.4
  #   ports:
  #     - 9200:9200
  #     - 9300:9300
  #   environment:
  #     - discovery.type=single-node
  #     - xpack.security.enabled=false
networks:
  facility: